from fastapi import FastAPI, HTTPException, Depends
from sqlalchemy.orm import Session
from . import models, schemas
from .db import SessionLocal, engine

# This line creates the tables in Postgres if they don't exist
models.Base.metadata.create_all(bind=engine)

app = FastAPI()

# Dependency to get a DB session (The "Bridge")
def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()

@app.get("/posts", response_model=list[schemas.PostResponse])
def get_posts(limit: int = 10, db: Session = Depends(get_db)):
    posts = db.query(models.Post).limit(limit).all()
    return posts

@app.get("/posts/{post_id}", response_model=schemas.PostResponse)
def get_post(post_id: int, db: Session = Depends(get_db)):
    post = db.query(models.Post).filter(models.Post.id == post_id).first()
    if not post:
        raise HTTPException(status_code=404, detail="Post not found")
    return post

@app.post("/posts", response_model=schemas.PostResponse)
def create_post(post: schemas.PostCreate, db: Session = Depends(get_db)):
    # Convert Pydantic model to SQLAlchemy Model
    new_post = models.Post(title=post.title, content=post.content)
    db.add(new_post)
    db.commit()
    db.refresh(new_post) # Gets the ID generated by Postgres
    return new_post


# ... (existing imports and get_db function)

# 1. UPDATE OPERATION
@app.put("/posts/{post_id}", response_model=schemas.PostResponse)
def update_post(post_id: int, updated_post: schemas.PostCreate, db: Session = Depends(get_db)):
    # Find the post
    post_query = db.query(models.Post).filter(models.Post.id == post_id)
    post = post_query.first()

    if post is None:
        raise HTTPException(status_code=404, detail="Post not found")

    # Update the fields
    post_query.update(updated_post.model_dump(), synchronize_session=False)

    db.commit()
    return post_query.first()


# 2. DELETE OPERATION
@app.delete("/posts/{post_id}", status_code=204)
def delete_post(post_id: int, db: Session = Depends(get_db)):
    # Find the post
    post_query = db.query(models.Post).filter(models.Post.id == post_id)
    post = post_query.first()

    if post is None:
        raise HTTPException(status_code=404, detail="Post not found")

    # Delete the post
    post_query.delete(synchronize_session=False)
    db.commit()

    # In DELETE, we usually return No Content (204)
    return None